# Generated by Django 5.0.6 on 2024-05-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Residential', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resident',
            new_name='Residentsdata',
        ),
    ]
