# Generated by Django 5.0.6 on 2024-05-27 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residential', '0002_rename_resident_residentsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiclesdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('car_number_plate', models.CharField(default='00000-0000000-0', max_length=150, unique=True)),
                ('carmodel', models.CharField(default='00000-0000000-0', max_length=100, unique=True)),
                ('entry_codes', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Residential.residentsdata')),
            ],
        ),
    ]
