# Generated by Django 5.0.6 on 2024-05-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Residential', '0005_guard_user_residentsdata_user_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guard',
            name='user',
        ),
    ]
