# Generated by Django 5.0.6 on 2024-05-31 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Residential', '0009_alter_residentsdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentsdata',
            name='email',
        ),
    ]
