# Generated by Django 5.0.6 on 2024-05-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_guard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='cnic_number',
            field=models.CharField(default='00000-0000000-0', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='household_members',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resident',
            name='apartment_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
