# Generated by Django 5.0.6 on 2024-05-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_resident_cnic_number_resident_household_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='household_members',
            field=models.CharField(max_length=10),
        ),
    ]
