# Generated by Django 5.0.6 on 2024-05-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_resident_household_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='household_members',
        ),
    ]
