# Generated by Django 5.0.6 on 2024-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vehicle_car_number_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='carmodel',
            field=models.CharField(default='00000-0000000-0', max_length=100, unique=True),
        ),
    ]
