# Generated by Django 5.0.6 on 2024-05-23 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_vehicle_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='age',
            field=models.CharField(default='00000-0000000-0', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='entry_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='numberofpersons',
            field=models.CharField(default='00000-0000000-0', max_length=25),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='entry_codes',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
