# Generated by Django 5.0.6 on 2024-05-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_resident_age_resident_entry_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='badge_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
